- name: Download bash_facilities
  git:
    repo=https://github.com/pedrocesar-ti/bash_facilities.git
    dest=/tmp/bash_facilities/
    version=master
    update=yes
  become: false
- name: Install bash_facilities
  shell: /tmp/bash_facilities/setup.sh
  become: false
