- name: Download Vimfiles
  git:
    repo=https://github.com/pedrocesar-ti/Vimfiles.git
    dest=/tmp/Vimfiles/
    version=master
    update=yes
  become: false
- name: Install Vimfiles
  shell: /tmp/Vimfiles/setup.sh
  become: false
